// Master ETF list - NSE codes + underlying only (prices fetched dynamically)
const ETF_CODES = [
  { nse_code: 'NSE:ITBEES', underlying: 'Nifty IT TRI' },
  { nse_code: 'NSE:NIFTYBEES', underlying: 'Nifty 50' },
  { nse_code: 'NSE:METALIETF', underlying: 'Nifty Metal Index' },
  { nse_code: 'NSE:PHARMABEES', underlying: 'Nifty Pharma TRI' },
  { nse_code: 'NSE:MIDCAPETF', underlying: 'Mirae Asset Mutual Fund - Mirae Asset Nifty Midcap 150 ETF' },
  { nse_code: 'NSE:PVTBANIETF', underlying: 'Nifty Private Bank Index' },
  { nse_code: 'NSE:MODEFENCE', underlying: 'Nifty India Defence Total Return Index' },
  { nse_code: 'NSE:SMALLCAP', underlying: 'Mirae Asset Nifty Smallcap 250 Momentum Quality 100 ETF' },
  { nse_code: 'NSE:HDFCSML250', underlying: 'HDFC NIFTY Smallcap 250 ETF' },
  { nse_code: 'NSE:PSUBNKBEES', underlying: 'Nifty PSU Bank' },
  { nse_code: 'NSE:ALPHA', underlying: 'NIFTY Alpha 50 Index' },
  { nse_code: 'NSE:QUAL30IETF', underlying: 'ICICI Prudential Nifty 200 Quality 30 ETF' },
  { nse_code: 'NSE:ALPL30IETF', underlying: 'Nifty Alpha Low-Volatility 30 Index' },
  { nse_code: 'NSE:SML100CASE', underlying: 'Nifty Smallcap 100 Index' },
  { nse_code: 'NSE:NEXT50IETF', underlying: 'Nifty Next 50' },
  { nse_code: 'NSE:MONIFTY500', underlying: 'Motilal Oswal Nifty 500 ETF' },
  { nse_code: 'NSE:TOP100CASE', underlying: 'Zerodha Nifty 100 ETF' },
  { nse_code: 'NSE:MOMENTUM50', underlying: 'Nifty 500 Momentum 50 Total Return Index' },
  { nse_code: 'NSE:BANKBEES', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:MOM30IETF', underlying: 'ICICI Prudential Nifty 200 Momentum 30 ETF' },
  { nse_code: 'NSE:FMCGIETF', underlying: 'Nifty FMCG Index' },
  { nse_code: 'NSE:CPSEETF', underlying: 'CPSE ETF' },
  { nse_code: 'NSE:OILIETF', underlying: 'Nifty Oil & Gas Index' },
  { nse_code: 'NSE:GROWWPOWER', underlying: 'BSE Power Index - TRI' },
  { nse_code: 'NSE:MON100', underlying: 'Nasdaq100' },
  { nse_code: 'NSE:MOM100', underlying: 'Nifty Midcap 100' },
  { nse_code: 'NSE:MOREALTY', underlying: 'Motilal Oswal Nifty Realty ETF' },
  { nse_code: 'NSE:LOWVOLIETF', underlying: 'Nifty 100 Low Volatility 30 Index' },
  { nse_code: 'NSE:MIDCAP', underlying: 'Nifty Midcap 50 Index' },
  { nse_code: 'NSE:FINIETF', underlying: 'ICICI Prudential Nifty Financial Services Ex-Bank ETF' },
  { nse_code: 'NSE:AUTOIETF', underlying: 'Nifty Auto Index' },
  { nse_code: 'NSE:MULTICAP', underlying: 'Nifty500 Multicap 50:25:25 Index' },
  { nse_code: 'NSE:ALPHAETF', underlying: 'Mirae Asset Nifty 200 Alpha 30 ETF' },
  { nse_code: 'NSE:MIDSMALL', underlying: 'Mirae Asset Nifty MidSmallcap400 Momentum Quality 100 ETF' },
  { nse_code: 'NSE:VAL30IETF', underlying: 'Nifty200 Value 30 Index' },
  { nse_code: 'NSE:MOCAPITAL', underlying: 'Nifty Capital Market Total Return Index' },
  { nse_code: 'NSE:TOP10ADD', underlying: 'Nifty Top 10 Equal Weight Index' },
  { nse_code: 'NSE:ICICIB22', underlying: 'S&P BSE BHARAT 22 index' },
  { nse_code: 'NSE:BSE500IETF', underlying: 'S&P BSE 500 index' },
  { nse_code: 'NSE:HEALTHY', underlying: 'Nifty Healthcare TRI' },
  { nse_code: 'NSE:GROWWRAIL', underlying: 'Nifty India Railways PSU Index' },
  { nse_code: 'NSE:GROWWNET', underlying: 'Index' },
  { nse_code: 'NSE:MOMENTUM30', underlying: 'Nifty 200 Momentum 30 Index' },
  { nse_code: 'NSE:AONETOTAL', underlying: 'Nifty Total Market Index' },
  { nse_code: 'NSE:MASPTOP50', underlying: 'S&P 500 Top 50 Total Return Index' },
  { nse_code: 'NSE:NIFTY100EW', underlying: 'Nifty 100 Equal Weight Index' },
  { nse_code: 'NSE:INFRAIETF', underlying: 'ICICI Prudential Nifty Infrastructure ETF' },
  { nse_code: 'NSE:ENERGY', underlying: 'Nifty Energy' },
  { nse_code: 'NSE:MIDSELIETF', underlying: 'S&P BSE Midcap Select Index' },
  { nse_code: 'NSE:MAFANG', underlying: 'NYSE FANG+ Total Return Index' },
  { nse_code: 'NSE:NV20IETF', underlying: 'Nifty50 Value 20' },
  { nse_code: 'NSE:MSCIINDIA', underlying: 'MSCI India Index' },
  { nse_code: 'NSE:BFSI', underlying: 'Nifty Financial Services Index' },
  { nse_code: 'NSE:SBINEQWETF', underlying: 'Nifty50 Equal Weight' },
  { nse_code: 'NSE:TOP15IETF', underlying: 'Nifty Top 15 Equal Weight Index' },
  { nse_code: 'NSE:CHEMICAL', underlying: 'Nifty Chemicals Index (TRI)' },
  { nse_code: 'NSE:GROWWEV', underlying: 'Nifty EV and New Age Automotive Index' },
  { nse_code: 'NSE:MONQ50', underlying: 'Nasdaq Q-50 Total Return Index' },
  { nse_code: 'NSE:AXISVALUE', underlying: 'Nifty500 Value 50 TRI' },
  { nse_code: 'NSE:HDFCSENSEX', underlying: 'SENSEX' },
  { nse_code: 'NSE:MAHKTECH', underlying: 'Hang Seng TECH Total Return Index' },
  { nse_code: 'NSE:CONSUMER', underlying: 'Nifty India New Age Consumption' },
  { nse_code: 'NSE:AONETMMQ50', underlying: 'Nifty Total Market Momentum Quality 50 TRI' },
  { nse_code: 'NSE:MOMIDMTM', underlying: 'Nifty Midcap 150 Momentum 50 Total Return Index' },
  { nse_code: 'NSE:MOVALUE', underlying: 'Motilal Oswal S&P BSE Enhanced Value ETF' },
  { nse_code: 'NSE:GROWWN200', underlying: 'Nifty 200 Index- Total Return Index' },
  { nse_code: 'NSE:CONSUMBEES', underlying: 'Nifty India Consumption TRI' },
  { nse_code: 'NSE:GROWWHOSPI', underlying: 'BSE Hospitals Index' },
  { nse_code: 'NSE:ABSLPSE', underlying: 'Aditya Birla Sun Life Nifty PSE ETF' },
  { nse_code: 'NSE:HNGSNGBEES', underlying: 'Hang Seng Index' },
  { nse_code: 'NSE:DEFENCE', underlying: 'BSE India Defence' },
  { nse_code: 'NSE:MAKEINDIA', underlying: 'Nifty India Manufacturing Total Return Index' },
  { nse_code: 'NSE:FLEXIADD', underlying: 'Nifty500 Flexicap Quality 30 TRI' },
  { nse_code: 'NSE:TNIDETF', underlying: 'Nifty India Digital Index' },
  { nse_code: 'NSE:ELM250', underlying: 'Nifty LargeMidcap 250 TRI' },
];

module.exports = ETF_CODES;
