// Master ETF list - NSE codes + underlying only (prices fetched dynamically)
const ETF_CODES = [
  { nse_code: 'NSE:ABSLBANETF', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:ABSLNN50ET', underlying: 'Nifty Next 50' },
  { nse_code: 'NSE:ALPHA', underlying: 'NIFTY Alpha 50 Index' },
  { nse_code: 'NSE:ALPHAETF', underlying: 'Mirae Asset Nifty 200 Alpha 30 ETF' },
  { nse_code: 'NSE:ALPL30IETF', underlying: 'Nifty Alpha Low-Volatility 30 Index' },
  { nse_code: 'NSE:AUTOBEES', underlying: 'Nifty Auto TRI' },
  { nse_code: 'NSE:AUTOIETF', underlying: 'Nifty Auto Index' },
  { nse_code: 'NSE:AXISGOLD', underlying: 'Gold' },
  { nse_code: 'NSE:AXISILVER', underlying: 'Silver' },
  { nse_code: 'NSE:AXISNIFTY', underlying: 'Nifty 50' },
  { nse_code: 'NSE:AXISTECETF', underlying: 'NIFTY IT Index' },
  { nse_code: 'NSE:BANKBEES', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:BANKBETF', underlying: 'Bajaj Finserv Nifty Bank ETF' },
  { nse_code: 'NSE:BANKIETF', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:BANKNIFTY1', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:BFSI', underlying: 'Nifty Financial Services Index' },
  { nse_code: 'NSE:BSE500IETF', underlying: 'S&P BSE 500 Index' },
  { nse_code: 'NSE:BSLGOLDETF', underlying: 'Gold' },
  { nse_code: 'NSE:BSLNIFTY', underlying: 'Nifty 50' },
  { nse_code: 'NSE:COMMOIETF', underlying: 'Nifty Commodities ETF' },
  { nse_code: 'NSE:CONSUMBEES', underlying: 'Nifty India Consumption TRI' },
  { nse_code: 'NSE:CONSUMIETF', underlying: 'Nifty India Consumption Index' },
  { nse_code: 'NSE:CPSEETF', underlying: 'CPSE ETF' },
  { nse_code: 'NSE:DIVOPPBEES', underlying: 'Nifty Dividend Opportunities 50 TRI' },
  { nse_code: 'NSE:EQUAL50ADD', underlying: 'NIFTY 50 Equal Weight Index' },
  { nse_code: 'NSE:FINIETF', underlying: 'Nifty Financial Services Ex-Bank ETF' },
  { nse_code: 'NSE:FMCGIETF', underlying: 'Nifty FMCG Index' },
  { nse_code: 'NSE:GOLDBEES', underlying: 'Gold' },
  { nse_code: 'NSE:GOLDCASE', underlying: 'Zerodha Gold ETF' },
  { nse_code: 'NSE:GOLDETF', underlying: 'Mirae Asset Gold ETF' },
  { nse_code: 'NSE:GOLDIETF', underlying: 'Gold' },
  { nse_code: 'NSE:GOLDSHARE', underlying: 'Gold' },
  { nse_code: 'NSE:HDFCBSE500', underlying: 'HDFC S&P BSE 500 ETF' },
  { nse_code: 'NSE:HDFCGOLD', underlying: 'Gold' },
  { nse_code: 'NSE:HDFCLOWVOL', underlying: 'HDFC NIFTY100 Low Volatility 30 ETF' },
  { nse_code: 'NSE:HDFCMID150', underlying: 'HDFC NIFTY Midcap 150 ETF' },
  { nse_code: 'NSE:HDFCMOMENT', underlying: 'HDFC NIFTY200 Momentum 30 ETF' },
  { nse_code: 'NSE:HDFCNEXT50', underlying: 'HDFC NIFTY NEXT 50 ETF' },
  { nse_code: 'NSE:HDFCNIF100', underlying: 'HDFC NIFTY 100 ETF' },
  { nse_code: 'NSE:HDFCNIFBAN', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:HDFCNIFIT', underlying: 'HDFC NIFTY IT ETF' },
  { nse_code: 'NSE:HDFCNIFTY', underlying: 'Nifty 50' },
  { nse_code: 'NSE:HDFCPSUBK', underlying: 'HDFC NIFTY PSU BANK ETF' },
  { nse_code: 'NSE:HDFCPVTBAN', underlying: 'HDFC NIFTY Private Bank ETF' },
  { nse_code: 'NSE:HDFCSENSEX', underlying: 'SENSEX' },
  { nse_code: 'NSE:HDFCSILVER', underlying: 'Silver' },
  { nse_code: 'NSE:HDFCSML250', underlying: 'HDFC NIFTY Smallcap 250 ETF' },
  { nse_code: 'NSE:HEALTHIETF', underlying: 'Nifty Healthcare Index' },
  { nse_code: 'NSE:HEALTHY', underlying: 'Nifty Healthcare TRI' },
  { nse_code: 'NSE:HNGSNGBEES', underlying: 'Hang Seng Index' },
  { nse_code: 'NSE:ICICIB22', underlying: 'S&P BSE BHARAT 22 Index' },
  { nse_code: 'NSE:INFRABEES', underlying: 'Nifty Infra' },
  { nse_code: 'NSE:INFRAIETF', underlying: 'Nifty Infrastructure ETF' },
  { nse_code: 'NSE:IT', underlying: 'NIFTY IT Index' },
  { nse_code: 'NSE:ITBEES', underlying: 'Nifty IT TRI' },
  { nse_code: 'NSE:ITETF', underlying: 'Mirae Asset Nifty IT ETF' },
  { nse_code: 'NSE:ITIETF', underlying: 'Nifty IT Index' },
  { nse_code: 'NSE:JUNIORBEES', underlying: 'Nifty Next 50' },
  { nse_code: 'NSE:LOWVOLIETF', underlying: 'Nifty 100 Low Volatility 30 Index' },
  { nse_code: 'NSE:MAFANG', underlying: 'NYSE FANG+ Total Return Index' },
  { nse_code: 'NSE:MAHKTECH', underlying: 'Hang Seng TECH Total Return Index' },
  { nse_code: 'NSE:MAKEINDIA', underlying: 'Nifty India Manufacturing TRI' },
  { nse_code: 'NSE:MASPTOP50', underlying: 'S&P 500 Top 50 Total Return Index' },
  { nse_code: 'NSE:MID150BEES', underlying: 'Nifty Midcap 150 TRI' },
  { nse_code: 'NSE:MIDCAP', underlying: 'Nifty Midcap 50 Index' },
  { nse_code: 'NSE:MIDCAPETF', underlying: 'Mirae Asset Nifty Midcap 150 ETF' },
  { nse_code: 'NSE:MIDCAPIETF', underlying: 'Nifty Midcap 150' },
  { nse_code: 'NSE:MIDQ50ADD', underlying: 'Nifty Midcap 150 Quality 50 Index' },
  { nse_code: 'NSE:MIDSELIETF', underlying: 'S&P BSE Midcap Select Index' },
  { nse_code: 'NSE:MNC', underlying: 'Kotak Nifty MNC ETF' },
  { nse_code: 'NSE:MOHEALTH', underlying: 'Motilal Oswal S&P BSE Healthcare ETF' },
  { nse_code: 'NSE:MOM100', underlying: 'Nifty Midcap 100' },
  { nse_code: 'NSE:MOM30IETF', underlying: 'Nifty 200 Momentum 30 ETF' },
  { nse_code: 'NSE:MOMENTUM', underlying: 'Nifty 200 Momentum 30 ETF (ABSL)' },
  { nse_code: 'NSE:MOMOMENTUM', underlying: 'Nifty 200 Momentum 30 TRI' },
  { nse_code: 'NSE:MON100', underlying: 'Nasdaq 100' },
  { nse_code: 'NSE:MONIFTY500', underlying: 'Motilal Oswal Nifty 500 ETF' },
  { nse_code: 'NSE:MONQ50', underlying: 'Nasdaq Q-50 Total Return Index' },
  { nse_code: 'NSE:MOREALTY', underlying: 'Motilal Oswal Nifty Realty ETF' },
  { nse_code: 'NSE:MOSMALL250', underlying: 'Motilal Oswal Nifty Smallcap 250 ETF' },
  { nse_code: 'NSE:MOVALUE', underlying: 'Motilal Oswal S&P BSE Enhanced Value ETF' },
  { nse_code: 'NSE:NEXT50IETF', underlying: 'Nifty Next 50' },
  { nse_code: 'NSE:NIF100BEES', underlying: 'Nifty 100 TRI' },
  { nse_code: 'NSE:NIF100IETF', underlying: 'Nifty 100' },
  { nse_code: 'NSE:NIFTY1', underlying: 'Nifty 50' },
  { nse_code: 'NSE:NIFTYBEES', underlying: 'Nifty 50' },
  { nse_code: 'NSE:NIFTYETF', underlying: 'Nifty 50' },
  { nse_code: 'NSE:NIFTYIETF', underlying: 'Nifty 50' },
  { nse_code: 'NSE:NIFTYQLITY', underlying: 'Nifty 200 Quality 30 ETF (ABSL)' },
  { nse_code: 'NSE:NV20', underlying: 'Nifty50 Value 20' },
  { nse_code: 'NSE:NV20BEES', underlying: 'Nifty50 Value20 TRI' },
  { nse_code: 'NSE:NV20IETF', underlying: 'Nifty50 Value 20' },
  { nse_code: 'NSE:PHARMABEES', underlying: 'Nifty Pharma TRI' },
  { nse_code: 'NSE:PSUBANK', underlying: 'Nifty PSU Bank' },
  { nse_code: 'NSE:PSUBNKBEES', underlying: 'Nifty PSU Bank' },
  { nse_code: 'NSE:PSUBNKIETF', underlying: 'Nifty PSU Bank ETF (ICICI)' },
  { nse_code: 'NSE:PVTBANIETF', underlying: 'Nifty Private Bank Index' },
  { nse_code: 'NSE:PVTBANKADD', underlying: 'DSP Nifty Private Bank ETF' },
  { nse_code: 'NSE:QGOLDHALF', underlying: 'Gold' },
  { nse_code: 'NSE:SBIETFCON', underlying: 'Nifty India Consumption Index (SBI)' },
  { nse_code: 'NSE:SBIETFIT', underlying: 'Nifty IT Index (SBI)' },
  { nse_code: 'NSE:SBIETFPB', underlying: 'Nifty Private Bank Index (SBI)' },
  { nse_code: 'NSE:SENSEXETF', underlying: 'Mirae Asset S&P BSE Sensex ETF' },
  { nse_code: 'NSE:SETFGOLD', underlying: 'Gold' },
  { nse_code: 'NSE:SETFNIF50', underlying: 'Nifty 50' },
  { nse_code: 'NSE:SETFNIFBK', underlying: 'Nifty Bank' },
  { nse_code: 'NSE:SETFNN50', underlying: 'Nifty Next 50' },
  { nse_code: 'NSE:SILVER', underlying: 'Silver' },
  { nse_code: 'NSE:SILVERADD', underlying: 'DSP Silver ETF' },
  { nse_code: 'NSE:SILVERBEES', underlying: 'Silver' },
  { nse_code: 'NSE:SILVERIETF', underlying: 'Silver' },
  { nse_code: 'NSE:SMALLCAP', underlying: 'Mirae Asset Nifty Smallcap 250 ETF' },
  { nse_code: 'NSE:TATAGOLD', underlying: 'Tata Gold ETF' },
  { nse_code: 'NSE:TATSILV', underlying: 'Tata Silver ETF' },
  { nse_code: 'NSE:TECH', underlying: 'Nifty IT TRI Index' },
  { nse_code: 'NSE:TNIDETF', underlying: 'Nifty India Digital Index' },
];

module.exports = ETF_CODES;
